version: "3"

services:

    apache:
        build: docker/apache/
        ports: [ "80" ]
        volumes:
            - .:/var/www/html
        networks:
            - backend
        depends_on:
            - php

    php:
        build: docker/php/
        volumes:
            - .:/var/www/html
        networks:
            - backend
        depends_on:
            - mysql
            - mailer
        command: bash -c "composer install && php-fpm"

    mysql:
        image: mysql
        command:
            - --default-authentication-plugin=mysql_native_password
        ports: [ "3306" ]
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: base_database
        volumes:
            - mysql:/var/lib/mysql
            - ./docker/mysql/data:/docker-entrypoint-initdb.d
        networks:
            - backend

#    node:
#        image: node:16
#        user: node
#        working_dir: /home/node/app
#        volumes:
#            - ./:/home/node/app
#        command: bash -c "npm install && npm run watch"

#    phpmyadmin:
#        image: phpmyadmin/phpmyadmin
#        ports: [ "80" ]
#        environment:
#            PMA_HOST: "mysql"
#            PMA_PORT: "3306"
#            PMA_USER: "root"
#            PMA_PASSWORD: "root"
#        depends_on:
#            - mysql

    mailer:
        image: schickling/mailcatcher
        ports: [ "1025", "1080" ]
        networks:
            - backend

networks:
    backend: ~

volumes:
    mysql: ~
